name: 'Terraform Apply'
description: 'Terraform Apply'
inputs:
  working-directory:
    required: true 
    description: working-directory
    default: dev

  role-to-assume:
    required: true
    description: role-to-assume

  aws-region:
    required: true
    description: role-to-assume
    default: us-east-1

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: OIDCSession

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      shell: bash
      working-directory: ./${{ inputs.working-directory }}

    # Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve
      shell: bash
      working-directory: ./${{ inputs.working-directory }}
